spring.application.name=distributed-job-scheduler

server.port=9090

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/distributed_job_scheduler
spring.datasource.username=postgres
spring.datasource.password=Mammu@4321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# JWT
jwt.secret=3F8A6E1D9B2C4F7A8E5D6C1B9A7F3E6D5C8A1F4B7E2D9C6A5F8B1E3D7C9A2F6B
jwt.expiration=86400000